[phases.setup]
nixPkgs = ["python310", "gcc", "libglvnd", "opencv"]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "uvicorn app:app --host 0.0.0.0 --port $PORT"
